name: Docker Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Container Image
      run: |
        docker build -t python-docker:latest .
        docker tag python-docker:latest  ghcr.io/akhan4u/python-docker:latest

    - name: Push to GHCR
      run: |
        export CR_PAT=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
        echo $CR_PAT | docker login ghcr.io -u akhan4u --password-stdin
        docker push ghcr.io/akhan4u/python-docker:latest
